# URL: https://xyz.sharepoint.com/:f:/r/sites/xyz


name: Up

### 以下内容请保持不变 (请修改下方的 环境变量设置)
on:
  repository_dispatch:
  workflow_dispatch:
    inputs:
      URL:
        description: 'URL'
        default: 'https://xx'
      NAME:
        description: 'NAME'
        default: 'fileCache'
      DIR:
        description: 'DIR [with "/" at start or end.]'
        default: 'Default Download/'
      DISKCLEAN:
        description: 'Clean Disk [True or False]'
        default: 'False'

jobs:
  Compile:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Set env
      run: |
        echo "URL=${{ github.event.inputs.URL }}" >> $GITHUB_ENV
        echo "NAME=${{ github.event.inputs.NAME }}" >> $GITHUB_ENV
        echo "DIR=${{ github.event.inputs.DIR }}" >> $GITHUB_ENV
        echo "DISKCLEAN=${{ github.event.inputs.DISKCLEAN }}" >> $GITHUB_ENV

    - name: Maximize Build Space
      uses: easimon/maximize-build-space@master
      if: env.DISKCLEAN == 'true'
      with:
        root-reserve-mb: 5120
        swap-size-mb: 512
        remove-dotnet: 'true'
        remove-android: 'true'

    - name: Download Files
      run: |
        wget "${{ env.URL }}" -O "${{ env.NAME }}"
        [ $? == 0 ] && echo "Result=true" >> $GITHUB_ENV || echo "Result=false" >> $GITHUB_ENV

    - name: Upload Files
      if: env.Result == 'true'&& !cancelled() 
      env: 
        ZIPPASSWORD: ${{ secrets.UNZIP_PASSWORD }}
      run: |
        cd data
        unzip -P ${{ env.ZIPPASSWORD }} data.zip
        cd ..
        export localfilename="${{ env.NAME }}"
        export remotefilename="${{ env.DIR }}${{ env.NAME }}"
        chmod +x ./oneup
        ./oneup
#      if: env.DELETE_OLD_WORKFLOW == 'true' && !cancelled()
    - name: Delete old Workflow Runs
      uses: GitRML/delete-workflow-runs@main
      with:
        retain_days: 1
        keep_minimum_runs: 2